package jogo_dados;

import javax.swing.JOptionPane;
import javax.swing.ImageIcon;


/**
 *
 * @author João-W10x64
 */
public class frm_telaInicio extends javax.swing.JFrame {

    /**
     * Creates new form frm_tela
     */
    public frm_telaInicio() {
        initComponents();
        
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        btnLancarDados = new javax.swing.JButton();
        dado_1 = new javax.swing.JLabel();
        dado_2 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(170, 130, 170, 130, new java.awt.Color(255, 255, 255)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/img_dadosHome.png"))); // NOI18N
        jPanel1.add(lblLogo);
        lblLogo.setBounds(90, 170, 310, 280);

        lblTitle1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblTitle1.setText("Jogo de Dados");
        jPanel1.add(lblTitle1);
        lblTitle1.setBounds(120, 90, 310, 50);

        btnLancarDados.setBackground(new java.awt.Color(0, 0, 0));
        btnLancarDados.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLancarDados.setForeground(new java.awt.Color(255, 255, 255));
        btnLancarDados.setText("Lançar dados");
        btnLancarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancarDadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnLancarDados);
        btnLancarDados.setBounds(140, 510, 180, 40);

        dado_1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(dado_1);
        dado_1.setBounds(60, 220, 150, 0);

        dado_2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(dado_2);
        dado_2.setBounds(270, 220, 150, 0);

        lblResultado.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPanel1.add(lblResultado);
        lblResultado.setBounds(150, 400, 260, 50);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void aplicarFacesDados(int[] resultadosFaces, int soma, String[] resultadoFinal ){
        lblLogo.setIcon(null);//ocultando a imagem da home
        
        //setando os valores de cada dado em sua respectiva variavel 
        int valorDado_1 = resultadosFaces[0];
        int valorDado_2 = resultadosFaces[1];
        
        //armazenando as imagens da face de cada cubo em variaveis de acordo com os valores passados anteriormente
        ImageIcon faceDado1 = new ImageIcon(getClass().getResource("/imagens/face_"+valorDado_1+".png"));
        ImageIcon faceDado2 = new ImageIcon(getClass().getResource("/imagens/face_"+valorDado_2+".png"));
        
        //posicionando o layout da imagens dos dados
        faceDado1.setImage(faceDado1.getImage().getScaledInstance(142, 142, 1));
        faceDado2.setImage(faceDado2.getImage().getScaledInstance(142, 142, 1));
             
        dado_1.setIcon(faceDado1);//setando a face do dado 1
        dado_1.setBounds(70, 215, 142, 142);//posicionando dado 1
        
        dado_2.setIcon(faceDado2);//setando a face do dado 2 
        dado_2.setBounds(260, 215, 142, 142);//posicionando dado 2   
        
        //exibindo a soma das faces       
        lblTitle1.setText("Soma das faces: " + Integer.toString(soma));
        lblTitle1.setBounds(85, 15, 410, 200);//posicionando a label
        
        //se o jogador ganhou
        if(resultadoFinal[0] == "Ganhou"){
            //posiciona o resultado com uma estilização
            lblResultado.setBounds(158, 400, 500, 100);
        }else{
            //posiciona o resultado com uma estilização
            lblResultado.setBounds(95, 400, 500, 100);
        }
        
        //exibe o resultado final
        lblResultado.setText(resultadoFinal[1]);
    }
    
    private void btnLancarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancarDadosActionPerformed
        // TODO add your handling code here: 
        //instanciando a classe dados
        Dados dados = new Dados();
        
        //lançando os dados e obtendo os resultados das faces
        int[] resultadosFaces = dados.lancarDados();
            
        //armazenando na variavel a soma dos resultado das faces 
        int soma = dados.somarFaces(resultadosFaces);
        
        //com o valor da soma, determina se o jogador ganhou ou perdeu
        String[] resultadoFinal = dados.resultado(soma);
        
        //chamando o metodo que organiza o layout e seta as imagens dos dados com base nos resultados das faces
        aplicarFacesDados(resultadosFaces, soma, resultadoFinal);
    }//GEN-LAST:event_btnLancarDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_telaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_telaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_telaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_telaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_telaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLancarDados;
    private javax.swing.JLabel dado_1;
    private javax.swing.JLabel dado_2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}
